export const BANKS = [
  { id: "bca", name: "Bank BCA", logo: "/banks/bca.png" },
  { id: "mandiri", name: "Bank Mandiri", logo: "/banks/mandiri.png" },
  { id: "bri", name: "Bank BRI", logo: "/banks/bri.png" },
  { id: "bni", name: "Bank BNI", logo: "/banks/bni.png" },
  { id: "cimb", name: "CIMB Niaga", logo: "/banks/cimb.png" },
  { id: "permata", name: "Bank Permata", logo: "/banks/permata.png" },
  { id: "danamon", name: "Bank Danamon", logo: "/banks/danamon.png" },
  { id: "btn", name: "Bank BTN", logo: "/banks/btn.png" },
  { id: "mega", name: "Bank Mega", logo: "/banks/mega.png" },
  { id: "maybank", name: "Maybank", logo: "/banks/maybank.png" },
] as const

export const EWALLETS = [
  { id: "gopay", name: "GoPay", logo: "/ewallet/gopay.png" },
  { id: "ovo", name: "OVO", logo: "/ewallet/ovo.png" },
  { id: "dana", name: "DANA", logo: "/ewallet/dana.png" },
  { id: "shopeepay", name: "ShopeePay", logo: "/ewallet/shopeepay.png" },
  { id: "linkaja", name: "LinkAja", logo: "/ewallet/linkaja.png" },
] as const

export const CAR_BRANDS = [
  "Toyota",
  "Honda",
  "Mitsubishi",
  "Suzuki",
  "Daihatsu",
  "Nissan",
  "Mazda",
  "Hyundai",
  "Kia",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Volkswagen",
  "Ford",
  "Chevrolet",
  "Tesla",
  "Wuling",
  "MG",
  "Chery",
] as const

export const LOCATIONS = [
  "Jakarta",
  "Surabaya",
  "Bandung",
  "Medan",
  "Semarang",
  "Makassar",
  "Palembang",
  "Tangerang",
  "Depok",
  "Bekasi",
  "Yogyakarta",
  "Malang",
  "Solo",
  "Denpasar",
  "Balikpapan",
] as const

export const KYC_BONUS_AMOUNT = 2500000

export const MIN_BID_INCREMENT = 100000

export const TESTIMONIALS_SAMPLE = [
  {
    id: "1",
    name: "Budi Santoso",
    location: "Jakarta Selatan",
    rating: 5,
    comment:
      "Alhamdulillah dapat Toyota Avanza 2021 dengan harga sangat kompetitif! Prosesnya mudah dan transparan. Tim LELANGMOBIL.COM sangat profesional dalam melayani.",
    vehicle: "Toyota Avanza G 2021",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "2",
    name: "Siti Rahayu",
    location: "Surabaya",
    rating: 5,
    comment:
      "Pertama kali ikut lelang mobil dan langsung berhasil! Dapat Honda CR-V 2020 kondisi excellent. Bonus KYC Rp 2.5 juta juga langsung masuk. Recommended!",
    vehicle: "Honda CR-V Turbo 2020",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "3",
    name: "Ahmad Hidayat",
    location: "Bandung",
    rating: 5,
    comment:
      "Platform lelang terbaik di Indonesia! Sudah 3x menang lelang di sini. Mobil yang dibeli selalu sesuai deskripsi. Customer service responsif 24/7.",
    vehicle: "Mitsubishi Xpander Ultimate 2022",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "4",
    name: "Dewi Lestari",
    location: "Medan",
    rating: 5,
    comment:
      "KYC diverifikasi cepat hanya 1 jam! Bonus langsung masuk dan bisa langsung ikut lelang. Berhasil dapat Xpander 2022 dengan harga dibawah pasaran 30 juta!",
    vehicle: "Mitsubishi Xpander Cross 2022",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "5",
    name: "Eko Prasetyo",
    location: "Semarang",
    rating: 5,
    comment:
      "Sistem lelang real-time sangat menarik! Bisa lihat langsung kompetitor bid berapa. Menang lelang BMW 320i dengan strategi bid di menit terakhir. Mantap!",
    vehicle: "BMW 320i Sport 2019",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "6",
    name: "Linda Wijaya",
    location: "Jakarta Utara",
    rating: 5,
    comment:
      "Proses dari lelang sampai pengiriman mobil sangat smooth. Dokumen lengkap, mobil diantar sampai rumah. Worth it banget!",
    vehicle: "Toyota Innova Reborn 2021",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "7",
    name: "Hendra Gunawan",
    location: "Tangerang",
    rating: 5,
    comment:
      "Dapat Innova Reborn 2021 dengan KM rendah 15rb! Kondisi seperti baru, interior rapih, mesin halus. Terima kasih LELANGMOBIL.COM!",
    vehicle: "Toyota Innova Reborn V 2021",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "8",
    name: "Ratna Sari",
    location: "Bekasi",
    rating: 5,
    comment:
      "Awalnya ragu ikut lelang online, tapi setelah coba ternyata aman dan terpercaya. Sertifikat BPKB juga asli dan proses balik nama lancar!",
    vehicle: "Honda Jazz RS 2020",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "9",
    name: "Bambang Susilo",
    location: "Yogyakarta",
    rating: 5,
    comment:
      "Harga lelang jauh lebih murah dari dealer! Hemat 40 juta untuk beli Fortuner 2020. Admin juga helpful banget jelasin step by step.",
    vehicle: "Toyota Fortuner VRZ 2020",
    avatar: "/placeholder.svg?height=48&width=48",
  },
  {
    id: "10",
    name: "Maya Kusuma",
    location: "Denpasar",
    rating: 5,
    comment:
      "Platform terdaftar OJK jadi ga worry soal keamanan. Deposit dan withdrawal juga cepat. Support team ramah dan informatif.",
    vehicle: "Mazda CX-5 2021",
    avatar: "/placeholder.svg?height=48&width=48",
  },
] as const

export const SAMPLE_VEHICLES = [
  {
    id: "v1",
    brand: "Toyota",
    model: "Avanza G",
    year: 2021,
    mileage: 35000,
    transmission: "Automatic" as const,
    fuel_type: "Bensin" as const,
    color: "Putih",
    starting_price: 150000000,
    current_bid: 168000000,
    condition: "Excellent" as const,
    location: "Jakarta",
    auction_status: "live" as const,
    auction_end_time: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    bid_count: 12,
    view_count: 245,
    images: ["/placeholder.svg?height=400&width=600"],
  },
  {
    id: "v2",
    brand: "Honda",
    model: "CR-V Turbo",
    year: 2020,
    mileage: 42000,
    transmission: "CVT" as const,
    fuel_type: "Bensin" as const,
    color: "Hitam",
    starting_price: 320000000,
    current_bid: 345000000,
    condition: "Good" as const,
    location: "Surabaya",
    auction_status: "live" as const,
    auction_end_time: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    bid_count: 8,
    view_count: 189,
    images: ["/placeholder.svg?height=400&width=600"],
  },
  {
    id: "v3",
    brand: "Mitsubishi",
    model: "Xpander Ultimate",
    year: 2022,
    mileage: 18000,
    transmission: "Automatic" as const,
    fuel_type: "Bensin" as const,
    color: "Silver",
    starting_price: 220000000,
    current_bid: 238000000,
    condition: "Excellent" as const,
    location: "Bandung",
    auction_status: "live" as const,
    auction_end_time: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    bid_count: 15,
    view_count: 312,
    images: ["/placeholder.svg?height=400&width=600"],
  },
  {
    id: "v4",
    brand: "BMW",
    model: "320i Sport",
    year: 2019,
    mileage: 55000,
    transmission: "Automatic" as const,
    fuel_type: "Bensin" as const,
    color: "Biru",
    starting_price: 450000000,
    current_bid: 478000000,
    condition: "Good" as const,
    location: "Jakarta",
    auction_status: "live" as const,
    auction_end_time: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    bid_count: 6,
    view_count: 156,
    images: ["/placeholder.svg?height=400&width=600"],
  },
  {
    id: "v5",
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    mileage: 8000,
    transmission: "Automatic" as const,
    fuel_type: "Electric" as const,
    color: "Merah",
    starting_price: 650000000,
    current_bid: 682000000,
    condition: "Excellent" as const,
    location: "Jakarta",
    auction_status: "live" as const,
    auction_end_time: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    bid_count: 4,
    view_count: 423,
    images: ["/placeholder.svg?height=400&width=600"],
  },
  {
    id: "v6",
    brand: "Suzuki",
    model: "Ertiga GX",
    year: 2021,
    mileage: 28000,
    transmission: "Automatic" as const,
    fuel_type: "Bensin" as const,
    color: "Abu-abu",
    starting_price: 180000000,
    current_bid: 195000000,
    condition: "Good" as const,
    location: "Yogyakarta",
    auction_status: "upcoming" as const,
    auction_start_time: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    auction_end_time: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    bid_count: 0,
    view_count: 89,
    images: ["/placeholder.svg?height=400&width=600"],
  },
] as const
