-- Generate 120 realistic testimonials with diverse feedback
INSERT INTO testimonials (user_id, vehicle_id, rating, comment, images, verified_purchase, is_featured, created_at) VALUES
-- 5 Star Reviews (80 testimonials)
(NULL, NULL, 5, 'Alhamdulillah dapat Toyota Avanza 2021 dengan harga sangat kompetitif! Prosesnya mudah dan transparan. Tim LELANGMOBIL.COM sangat profesional dalam melayani.', '{}', true, true, NOW() - INTERVAL '1 day'),
(NULL, NULL, 5, 'Pertama kali ikut lelang mobil dan langsung berhasil! Dapat Honda CR-V 2020 kondisi excellent. Bonus KYC Rp 2.5 juta juga langsung masuk. Recommended!', '{}', true, true, NOW() - INTERVAL '2 days'),
(NULL, NULL, 5, 'Platform lelang terbaik di Indonesia! Sudah 3x menang lelang di sini. Mobil yang dibeli selalu sesuai deskripsi. Customer service responsif 24/7.', '{}', true, true, NOW() - INTERVAL '3 days'),
(NULL, NULL, 5, 'KYC diverifikasi cepat hanya 1 jam! Bonus langsung masuk dan bisa langsung ikut lelang. Berhasil dapat Xpander 2022 dengan harga dibawah pasaran 30 juta!', '{}', true, false, NOW() - INTERVAL '4 days'),
(NULL, NULL, 5, 'Sistem lelang real-time sangat menarik! Bisa lihat langsung kompetitor bid berapa. Menang lelang BMW 320i dengan strategi bid di menit terakhir. Mantap!', '{}', true, false, NOW() - INTERVAL '5 days'),
(NULL, NULL, 5, 'Proses dari lelang sampai pengiriman mobil sangat smooth. Dokumen lengkap, mobil diantar sampai rumah. Worth it banget!', '{}', true, false, NOW() - INTERVAL '6 days'),
(NULL, NULL, 5, 'Dapat Innova Reborn 2021 dengan KM rendah 15rb! Kondisi seperti baru, interior rapih, mesin halus. Terima kasih LELANGMOBIL.COM!', '{}', true, false, NOW() - INTERVAL '7 days'),
(NULL, NULL, 5, 'Awalnya ragu ikut lelang online, tapi setelah coba ternyata aman dan terpercaya. Sertifikat BPKB juga asli dan proses balik nama lancar!', '{}', true, false, NOW() - INTERVAL '8 days'),
(NULL, NULL, 5, 'Harga lelang jauh lebih murah dari dealer! Hemat 40 juta untuk beli Fortuner 2020. Admin juga helpful banget jelasin step by step.', '{}', true, false, NOW() - INTERVAL '9 days'),
(NULL, NULL, 5, 'Platform terdaftar OJK jadi ga worry soal keamanan. Deposit dan withdrawal juga cepat. Support team ramah dan informatif.', '{}', true, false, NOW() - INTERVAL '10 days'),
(NULL, NULL, 5, 'Fitur bid otomatis sangat membantu! Ga perlu standby terus di laptop. Set max bid dan sistem akan bid otomatis. Menang lelang Pajero Sport!', '{}', true, true, NOW() - INTERVAL '11 days'),
(NULL, NULL, 5, 'Kondisi mobil 100% sesuai dengan foto dan deskripsi. Tidak ada hidden damage. Tim inspeksi LELANGMOBIL.COM sangat teliti!', '{}', true, false, NOW() - INTERVAL '12 days'),
(NULL, NULL, 5, 'Pertama kali beli mobil bekas tapi kondisinya kayak baru! Service record lengkap, buku manual ada, ban masih tebal. Puas banget!', '{}', true, false, NOW() - INTERVAL '13 days'),
(NULL, NULL, 5, 'Ga nyangka bisa dapat Mercedes C200 2019 dengan budget segini. Lelang emang solusi beli mobil premium dengan harga terjangkau!', '{}', true, false, NOW() - INTERVAL '14 days'),
(NULL, NULL, 5, 'Sistem pembayarannya fleksibel. Bisa transfer ke berbagai bank. Konfirmasi pembayaran juga cepat kurang dari 2 jam sudah diverifikasi!', '{}', true, false, NOW() - INTERVAL '15 days'),
(NULL, NULL, 5, 'Dapat Jazz RS 2020 warna favorit! Mesin terawat banget, interior bersih. Harga menang lelang 35 juta lebih murah dari OLX!', '{}', true, false, NOW() - INTERVAL '16 days'),
(NULL, NULL, 5, 'CS nya helpful banget! Dikasih tips strategi bid yang efektif. Akhirnya menang lelang Civic Turbo impian dengan harga pas!', '{}', true, false, NOW() - INTERVAL '17 days'),
(NULL, NULL, 5, 'Mobilnya sudah dicek full inspection sebelum lelang. Laporan kondisi mobil detail banget. Jadi yakin sebelum bid!', '{}', true, false, NOW() - INTERVAL '18 days'),
(NULL, NULL, 5, 'Bonus KYC beneran masuk! Langsung dipake buat deposit ikut lelang. Sistem bonus ini sangat membantu pemula seperti saya!', '{}', true, false, NOW() - INTERVAL '19 days'),
(NULL, NULL, 5, 'Proses balik nama dibantu sama tim LELANGMOBIL.COM. Ga ribet urus sendiri. Service after sales nya bagus!', '{}', true, false, NOW() - INTERVAL '20 days'),
(NULL, NULL, 5, 'Mobil dikirim pakai car carrier profesional. Sampai rumah kondisi aman, ga ada lecet sama sekali. Pengalaman beli mobil terbaik!', '{}', true, false, NOW() - INTERVAL '21 days'),
(NULL, NULL, 5, 'Website mudah digunakan, tampilan modern. Info lelang lengkap dengan countdown timer. Notifikasi real-time juga berfungsi baik!', '{}', true, false, NOW() - INTERVAL '22 days'),
(NULL, NULL, 5, 'Dapat Ertiga 2021 untuk keluarga dengan harga 25 juta dibawah showroom. Kondisi interior rapih, AC dingin, mesin prima!', '{}', true, false, NOW() - INTERVAL '23 days'),
(NULL, NULL, 5, 'Sistem lelang transparan, semua bid history bisa dilihat. Ga ada kecurangan. Trust system nya bagus!', '{}', true, false, NOW() - INTERVAL '24 days'),
(NULL, NULL, 5, 'KM mobil sesuai dengan yang tercatat di odo. Tidak ada manipulasi KM. Kejujuran LELANGMOBIL.COM patut diacungi jempol!', '{}', true, false, NOW() - INTERVAL '25 days'),
(NULL, NULL, 5, 'Berhasil jual mobil lama lewat LELANGMOBIL.COM dengan harga tinggi! Proses cepat, pembayaran aman. Recommended untuk seller juga!', '{}', true, false, NOW() - INTERVAL '26 days'),
(NULL, NULL, 5, 'Chat CS responsif 24/7. Tengah malam tanya-tanya juga dibalas. Very helpful dan sabar jelasin sampai detail!', '{}', true, false, NOW() - INTERVAL '27 days'),
(NULL, NULL, 5, 'Dapat CRV Prestige 2021 hitam metalik kondisi mulus! Interior kulit asli masih wangi. Maintenance record lengkap dari dealer resmi!', '{}', true, false, NOW() - INTERVAL '28 days'),
(NULL, NULL, 5, 'Proses refund deposit cepat ketika ga menang lelang. Langsung masuk ke rekening dalam 1 hari. Sistem payment terpercaya!', '{}', true, false, NOW() - INTERVAL '29 days'),
(NULL, NULL, 5, 'Foto mobil di website high quality dan banyak angle. Video 360 juga tersedia. Jadi bisa cek kondisi mobil dengan detail sebelum bid!', '{}', true, false, NOW() - INTERVAL '30 days'),
(NULL, NULL, 5, 'Dapat Terios 2020 untuk off-road hobby! Kondisi suspensi masih bagus, ban AT masih tebal. Perfect untuk adventure!', '{}', true, false, NOW() - INTERVAL '31 days'),
(NULL, NULL, 5, 'Harga starting bid wajar, ga kemahalan. Jadi bisa dapet mobil dengan harga reasonable. Transparansi harga yang baik!', '{}', true, false, NOW() - INTERVAL '32 days'),
(NULL, NULL, 5, 'Test drive bisa diatur sebelum lelang dimulai. Jadi yakin dengan kondisi mesin dan performa mobil. Service excellent!', '{}', true, false, NOW() - INTERVAL '33 days'),
(NULL, NULL, 5, 'Dapat Xpander Cross 2021 hitam metalik! Perfect family car dengan fitur lengkap. Hemat BBM juga!', '{}', true, false, NOW() - INTERVAL '34 days'),
(NULL, NULL, 5, 'Menang lelang Rush TRD 2020! Sporty dan cocok untuk daily driver. Mesin Toyota memang awet dan bandel!', '{}', true, false, NOW() - INTERVAL '35 days'),
(NULL, NULL, 5, 'Proses inspeksi pra-lelang sangat detail. 200 point checklist membuat saya yakin dengan kondisi mobil!', '{}', true, false, NOW() - INTERVAL '36 days'),
(NULL, NULL, 5, 'Video test drive tersedia di listing. Sangat membantu untuk assess kondisi mesin dan handling!', '{}', true, false, NOW() - INTERVAL '37 days'),
(NULL, NULL, 5, 'Garansi mesin 30 hari! Safety net yang bagus untuk buyer. Menunjukkan confidence seller terhadap produk!', '{}', true, false, NOW() - INTERVAL '38 days'),
(NULL, NULL, 5, 'Dapat BRV Prestige 2021! Interior premium dengan fitur Honda Sensing. Technology canggih!', '{}', true, false, NOW() - INTERVAL '39 days'),
(NULL, NULL, 5, 'Financing option tersedia! Bisa kredit dengan rate kompetitif. Flexible payment solution!', '{}', true, false, NOW() - INTERVAL '40 days'),
(NULL, NULL, 5, 'Trade-in mobil lama accepted! Praktis ga perlu jual mobil lama dulu. One-stop solution!', '{}', true, false, NOW() - INTERVAL '41 days'),
(NULL, NULL, 5, 'Dapat Alphard 2019 dengan harga 100 juta lebih murah! Luxury van impian terwujud!', '{}', true, false, NOW() - INTERVAL '42 days'),
(NULL, NULL, 5, 'Extended warranty bisa dibeli! Peace of mind untuk long-term ownership. Worth the investment!', '{}', true, false, NOW() - INTERVAL '43 days'),
(NULL, NULL, 5, 'Pickup service tersedia! Mobil diambil dari lokasi saya. Convenient banget!', '{}', true, false, NOW() - INTERVAL '44 days'),
(NULL, NULL, 5, 'Dapat Fortuner VRZ 2020 diesel! Powerful dan efficient. Perfect untuk family trip!', '{}', true, false, NOW() - INTERVAL '45 days'),
(NULL, NULL, 5, 'Free first service included! Value added yang bagus. Caring after sales support!', '{}', true, false, NOW() - INTERVAL '46 days'),
(NULL, NULL, 5, 'Dapat Voxy 2019 imported! Rare unit dengan kondisi mint. Happy banget!', '{}', true, false, NOW() - INTERVAL '47 days'),
(NULL, NULL, 5, 'Mobile inspection service! Team datang ke rumah untuk cek mobil. Very convenient!', '{}', true, false, NOW() - INTERVAL '48 days'),
(NULL, NULL, 5, 'Dapat Land Cruiser 2018! Beast mode activated. Off-road capability excellent!', '{}', true, false, NOW() - INTERVAL '49 days'),
(NULL, NULL, 5, 'Loyalty program bagus! Point bisa dipakai untuk discount bid berikutnya. Repeat customer friendly!', '{}', true, false, NOW() - INTERVAL '50 days'),
(NULL, NULL, 5, 'Dapat Harrier 2020! Premium SUV dengan luxury features. Japanese quality!', '{}', true, false, NOW() - INTERVAL '51 days'),
(NULL, NULL, 5, 'Referral bonus menarik! Ajak teman dapat cash reward. Win-win situation!', '{}', true, false, NOW() - INTERVAL '52 days'),
(NULL, NULL, 5, 'Dapat Camry 2021 hybrid! Fuel efficient dan comfortable. Technology advanced!', '{}', true, false, NOW() - INTERVAL '53 days'),
(NULL, NULL, 5, 'Virtual showroom available! 3D view sangat detail. Innovation yang bagus!', '{}', true, false, NOW() - INTERVAL '54 days'),
(NULL, NULL, 5, 'Dapat Pajero Dakar 2020! Legendary 4x4 dengan performa mantap!', '{}', true, false, NOW() - INTERVAL '55 days'),
(NULL, NULL, 5, 'Live auction system seru! Real-time bidding creates excitement. Engaging experience!', '{}', true, false, NOW() - INTERVAL '56 days'),
(NULL, NULL, 5, 'Dapat Outlander PHEV 2021! Eco-friendly plug-in hybrid. Future of mobility!', '{}', true, false, NOW() - INTERVAL '57 days'),
(NULL, NULL, 5, 'Insurance comparison tool helpful! Bisa compare rates dari berbagai provider. Time saver!', '{}', true, false, NOW() - INTERVAL '58 days'),
(NULL, NULL, 5, 'Dapat Accord 2020! Executive sedan dengan performa sporty. Perfect combination!', '{}', true, false, NOW() - INTERVAL '59 days'),
(NULL, NULL, 5, 'Bid reminder notification useful! Never miss auction deadline. Smart feature!', '{}', true, false, NOW() - INTERVAL '60 days'),
(NULL, NULL, 5, 'Dapat X-Trail 2021! Reliable family SUV dengan fitur safety lengkap!', '{}', true, false, NOW() - INTERVAL '61 days'),
(NULL, NULL, 5, 'Price history chart helpful! Bisa lihat trend harga untuk strategic bidding!', '{}', true, false, NOW() - INTERVAL '62 days'),
(NULL, NULL, 5, 'Dapat Mazda CX-5 2021! Premium interior dengan Skyactiv technology!', '{}', true, false, NOW() - INTERVAL '63 days'),
(NULL, NULL, 5, 'Market value indicator accurate! Helps determine fair bidding price!', '{}', true, false, NOW() - INTERVAL '64 days'),
(NULL, NULL, 5, 'Dapat Wuling Almaz RS 2022! Feature-rich dengan harga terjangkau!', '{}', true, false, NOW() - INTERVAL '65 days'),
(NULL, NULL, 5, 'Auction schedule flexible! Various time slots untuk accommodate semua orang!', '{}', true, false, NOW() - INTERVAL '66 days'),
(NULL, NULL, 5, 'Dapat Isuzu MU-X 2020! Tough SUV dengan performa diesel excellent!', '{}', true, false, NOW() - INTERVAL '67 days'),
(NULL, NULL, 5, 'Community forum aktif! Bisa sharing experience dengan bidder lain. Helpful community!', '{}', true, false, NOW() - INTERVAL '68 days'),
(NULL, NULL, 5, 'Dapat BMW X1 2020! Premium German engineering dengan luxury features!', '{}', true, false, NOW() - INTERVAL '69 days'),
(NULL, NULL, 5, 'Expert tips & guides comprehensive! Learn bidding strategies dari pro!', '{}', true, false, NOW() - INTERVAL '70 days'),
(NULL, NULL, 5, 'Dapat Audi A4 2019! Sophisticated design dengan technology advanced!', '{}', true, false, NOW() - INTERVAL '71 days'),
(NULL, NULL, 5, 'Success rate analytics helpful! Track winning vs losing bids untuk improvement!', '{}', true, false, NOW() - INTERVAL '72 days'),
(NULL, NULL, 5, 'Dapat Mazda 3 2021! Sporty sedan dengan handling excellent!', '{}', true, false, NOW() - INTERVAL '73 days'),
(NULL, NULL, 5, 'Bid history transparent! Bisa learn dari successful bids orang lain!', '{}', true, false, NOW() - INTERVAL '74 days'),
(NULL, NULL, 5, 'Dapat Toyota Sienta 2020! Compact MPV perfect untuk urban family!', '{}', true, false, NOW() - INTERVAL '75 days'),
(NULL, NULL, 5, 'Mobile app smooth! Bisa bid from anywhere. Convenience maksimal!', '{}', true, false, NOW() - INTERVAL '76 days'),
(NULL, NULL, 5, 'Dapat Suzuki XL7 2021! Affordable 7-seater dengan fitur modern!', '{}', true, false, NOW() - INTERVAL '77 days'),
(NULL, NULL, 5, 'Push notification timely! Always informed tentang auction status!', '{}', true, false, NOW() - INTERVAL '78 days'),
(NULL, NULL, 5, 'Dapat Daihatsu Terios R 2020! Reliable compact SUV untuk adventure!', '{}', true, false, NOW() - INTERVAL '79 days'),
(NULL, NULL, 5, 'Customer portal user-friendly! Easy to manage bids dan transactions!', '{}', true, false, NOW() - INTERVAL '80 days'),

-- 4 Star Reviews (30 testimonials)
(NULL, NULL, 4, 'Mobil bagus tapi pengiriman delay 3 hari. Communication bisa diperbaiki. Overall masih recommended!', '{}', true, false, NOW() - INTERVAL '81 days'),
(NULL, NULL, 4, 'Dapat Avanza 2020 dengan harga bagus. Minor scratches not disclosed but acceptable. Value for money!', '{}', true, false, NOW() - INTERVAL '82 days'),
(NULL, NULL, 4, 'Proses KYC agak lama 2 hari. Tapi customer service helpful. Eventually resolved!', '{}', true, false, NOW() - INTERVAL '83 days'),
(NULL, NULL, 4, 'Cat ada touch-up di beberapa bagian. Should be mentioned in description. But mechanically sound!', '{}', true, false, NOW() - INTERVAL '84 days'),
(NULL, NULL, 4, 'Deposit refund process could be faster. Took 4 days instead of promised 24 hours. But got it eventually!', '{}', true, false, NOW() - INTERVAL '85 days'),
(NULL, NULL, 4, 'Interior ada bekas pemakaian wajar. Deep cleaning needed. Tapi harga sudah compensate!', '{}', true, false, NOW() - INTERVAL '86 days'),
(NULL, NULL, 4, 'AC kurang dingin perlu service. Minor issue tapi should be checked before listing!', '{}', true, false, NOW() - INTERVAL '87 days'),
(NULL, NULL, 4, 'Website kadang slow saat peak hour. Infrastructure upgrade needed. But functional!', '{}', true, false, NOW() - INTERVAL '88 days'),
(NULL, NULL, 4, 'Foto bisa lebih banyak angle. Terutama for problem areas. Transparency bisa ditingkatkan!', '{}', true, false, NOW() - INTERVAL '89 days'),
(NULL, NULL, 4, 'Kalah bid 4x sebelum menang. Competition ketat! Persistence pays off!', '{}', true, false, NOW() - INTERVAL '90 days'),
(NULL, NULL, 4, 'Ban perlu ganti 2 buah. Maintenance cost not budgeted. Should be clearer in inspection!', '{}', true, false, NOW() - INTERVAL '91 days'),
(NULL, NULL, 4, 'Customer service response time bervariasi. Sometimes fast, sometimes slow. Consistency needed!', '{}', true, false, NOW() - INTERVAL '92 days'),
(NULL, NULL, 4, 'Proses balik nama butuh follow-up. Not as seamless as promised. But doable!', '{}', true, false, NOW() - INTERVAL '93 days'),
(NULL, NULL, 4, 'Harga akhir mendekati market price. Saving tidak sebesar expected. But process convenient!', '{}', true, false, NOW() - INTERVAL '94 days'),
(NULL, NULL, 4, 'Audio system perlu upgrade. Standard equipment basic. But car running well!', '{}', true, false, NOW() - INTERVAL '95 days'),
(NULL, NULL, 4, 'Velg ada grepes. Cosmetic issue not mentioned. Minor but should disclose!', '{}', true, false, NOW() - INTERVAL '96 days'),
(NULL, NULL, 4, 'Engine oil service due. Maintenance schedule should be shared. Planning needed!', '{}', true, false, NOW() - INTERVAL '97 days'),
(NULL, NULL, 4, 'Kaca film bubbling. Need replacement soon. Additional cost to consider!', '{}', true, false, NOW() - INTERVAL '98 days'),
(NULL, NULL, 4, 'Interior smell dari previous owner. Needs airing out. Cleaning helps!', '{}', true, false, NOW() - INTERVAL '99 days'),
(NULL, NULL, 4, 'Dashboard plastic ada lecet. Minor wear and tear. Acceptable untuk second hand!', '{}', true, false, NOW() - INTERVAL '100 days'),
(NULL, NULL, 4, 'Shock absorber agak keras. Comfort bisa better. May need replacement!', '{}', true, false, NOW() - INTERVAL '101 days'),
(NULL, NULL, 4, 'Turn signal intermittent. Electrical issue minor. Easy fix!', '{}', true, false, NOW() - INTERVAL '102 days'),
(NULL, NULL, 4, 'Power window slow. Regulator may need service. Function still ok!', '{}', true, false, NOW() - INTERVAL '103 days'),
(NULL, NULL, 4, 'Hood paint fading. Sun damage. Repaint one panel fixes it!', '{}', true, false, NOW() - INTERVAL '104 days'),
(NULL, NULL, 4, 'Central lock occasional error. Electronics aging. Manual backup works!', '{}', true, false, NOW() - INTERVAL '105 days'),
(NULL, NULL, 4, 'Carpet worn. Replacement needed. Cosmetic upgrade!', '{}', true, false, NOW() - INTERVAL '106 days'),
(NULL, NULL, 4, 'Speedometer backlight dim. LED replacement needed. Small fix!', '{}', true, false, NOW() - INTERVAL '107 days'),
(NULL, NULL, 4, 'CD player not working. Bluetooth works fine. Modern alternative!', '{}', true, false, NOW() - INTERVAL '108 days'),
(NULL, NULL, 4, 'Wiper blade needs replacement. Consumable part. Regular maintenance!', '{}', true, false, NOW() - INTERVAL '109 days'),
(NULL, NULL, 4, 'Side mirror loose. Tightening bolts helps. Minor adjustment!', '{}', true, false, NOW() - INTERVAL '110 days'),

-- 3 Star Reviews (10 testimonials)
(NULL, NULL, 3, 'Proses balik nama very complicated. Need simplification. Mobil ok though!', '{}', true, false, NOW() - INTERVAL '111 days'),
(NULL, NULL, 3, 'Saving minimal compared to market. Auction advantage not significant!', '{}', true, false, NOW() - INTERVAL '112 days'),
(NULL, NULL, 3, 'Kalah bid repeatedly. Frustrating experience. Finally won but exhausting!', '{}', true, false, NOW() - INTERVAL '113 days'),
(NULL, NULL, 3, 'Payment verification slow. Worry about fund safety. Communication gap!', '{}', true, false, NOW() - INTERVAL '114 days'),
(NULL, NULL, 3, 'Interior condition below expectation. Photos misleading. Reality check needed!', '{}', true, false, NOW() - INTERVAL '115 days'),
(NULL, NULL, 3, 'Multiple repairs needed. Budget underestimated. Disclosure could be better!', '{}', true, false, NOW() - INTERVAL '116 days'),
(NULL, NULL, 3, 'Customer service inconsistent. Response time varies too much. Improvement needed!', '{}', true, false, NOW() - INTERVAL '117 days'),
(NULL, NULL, 3, 'Website performance poor during peak. Technical issues frequent. Upgrade infrastructure!', '{}', true, false, NOW() - INTERVAL '118 days'),
(NULL, NULL, 3, 'Photo documentation insufficient. Need more angles and details. Transparency lacking!', '{}', true, false, NOW() - INTERVAL '119 days'),
(NULL, NULL, 3, 'Delivery delayed significantly. Updates not provided. Logistics needs work!', '{}', true, false, NOW() - INTERVAL '120 days')

ON CONFLICT DO NOTHING;

-- Update testimonials to use realistic user IDs from actual registered users if they exist
-- This would be run after users are created in the system
